# Generated by Django 2.2.1 on 2019-05-29 05:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190528_1851'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_ky',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_tr',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='father'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_ky',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='father'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_tr',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='father'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address_en',
            field=models.TextField(blank=True, null=True, verbose_name='home address'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address_ky',
            field=models.TextField(blank=True, null=True, verbose_name='home address'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address_tr',
            field=models.TextField(blank=True, null=True, verbose_name='home address'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='mother'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_ky',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='mother'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tr',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='mother'),
        ),
    ]
