# Generated by Django 2.1.7 on 2019-05-10 12:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190510_1204'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher_ru',
        ),
    ]
