# Generated by Django 2.2.1 on 2019-06-26 05:03

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190608_2209'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996999999'. Up to 15 digits allowed", regex='^\\+?996?\\d{9,15}$'), django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996999999'. Up to 15 digits allowed", regex='^\\0?\\d{9,10}$'), django.core.validators.RegexValidator(message='Please type in the correct format.', regex='^\\+?90\\d{10, 12}$')], verbose_name='phone'),
        ),
    ]
