# Generated by Django 2.1.7 on 2019-05-11 10:03

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190511_0923'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_ru',
        ),
    ]
