# Generated by Django 2.2.1 on 2019-06-27 03:44

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190626_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user',), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('user',), 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id', 'username'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996999999'. Up to 15 digits allowed", regex='^\\+?996?\\d{9,15}$'), django.core.validators.RegexValidator(message='Please type in the correct format.', regex='^\\+?90\\d{10, 12}$')], verbose_name='phone'),
        ),
    ]
