# Generated by Django 2.1.7 on 2019-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='annotation_en',
            field=models.TextField(null=True, verbose_name='annotation'),
        ),
        migrations.AddField(
            model_name='post',
            name='annotation_ru',
            field=models.TextField(null=True, verbose_name='annotation'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='post',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
