# Generated by Django 2.1.7 on 2019-05-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190510_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='notification',
            name='name_en',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='notification',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='name'),
        ),
    ]
