# Generated by Django 2.1.7 on 2019-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='state_en',
            field=models.CharField(choices=[('ZD', 'Necessary'), ('SD', 'Optional')], max_length=5, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='state_ru',
            field=models.CharField(choices=[('ZD', 'Necessary'), ('SD', 'Optional')], max_length=5, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expire',
            field=models.DateTimeField(verbose_name='date of expire'),
        ),
    ]
