# Generated by Django 2.1.7 on 2019-05-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190511_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='state_en',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='state_ru',
        ),
    ]
