# Generated by Django 2.1.7 on 2019-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190511_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
