# Generated by Django 2.2.1 on 2019-05-24 03:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190522_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'verbose_name': 'Wallpaper', 'verbose_name_plural': 'Wallpapers'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name_ru',
            new_name='name_ky',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='content_ru',
            new_name='content_ky',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='name_ru',
            new_name='name_ky',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='annotation_ru',
            new_name='annotation_ky',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_ru',
            new_name='content_ky',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name_ru',
            new_name='name_ky',
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='name_tr',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='post',
            name='annotation_tr',
            field=models.TextField(null=True, verbose_name='annotation'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
