# Generated by Django 2.2.1 on 2019-06-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190602_1902'),
        ('main', '0013_auto_20190526_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Teacher', verbose_name='teacher'),
        ),
    ]
