# Generated by Django 2.2.1 on 2019-06-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190608_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10, verbose_name='room')),
                ('day', models.CharField(choices=[('Monday', 'Monday')], max_length=15, verbose_name='day')),
                ('start_time', models.CharField(choices=[('8:00', '8:00'), ('8:55', '8:55'), ('9:50', '9:50'), ('10:45', '10:45'), ('11:40', '11:40'), ('12:35', '12:35'), ('13:30', '13:30'), ('14:25', '14:25'), ('15:20', '15:20'), ('16:15', '16:15'), ('17:10', '17:10')], max_length=5, verbose_name='start time')),
                ('end_time', models.CharField(choices=[('8:45', '8:45'), ('9:40', '9:40'), ('10:35', '10:35'), ('11:30', '11:30'), ('12:25', '12:25'), ('13:20', '13:20'), ('14:15', '14:15'), ('15:10', '15:10'), ('16:05', '16:05'), ('17:00', '17:00'), ('17:55', '17:55')], max_length=5, verbose_name='end time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assign_set', to='main.Lesson', verbose_name='lesson')),
            ],
        ),
    ]
