# Generated by Django 2.2.1 on 2019-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15, verbose_name='day'),
        ),
    ]
