# Generated by Django 2.2.1 on 2019-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190619_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='room',
            field=models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('118', '118'), ('119', '119')], max_length=10, verbose_name='room'),
        ),
    ]
