# Generated by Django 2.2.1 on 2019-06-26 20:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190627_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='topics'),
        ),
    ]
